"""Public import boundary for topology-gated recursive-model research.

The names defined directly here are dependency-light contracts from
``topology_gate.types``. Numerical worker implementations remain lazy exports:
requesting one imports only that worker, and a missing optional numerical stack
produces an actionable installation error.

``GateStatus``, ``BacktestConfig``, ``BacktestResult``, and ``TopologyResult``
are the canonical root contract names. Worker-specific objects that used to
collide with those names are available with explicit names such as
``PromotionGateStatus``, ``WalkForwardResult``, and ``DetectedTopologyResult``.
"""

from importlib import import_module
from typing import Any

from .asof import (
    ASOF_BOOK_SCHEMA,
    ASOF_BOOK_VERSION,
    LABEL_PRECEDENCE,
    MARKET_PRECEDENCE,
    UNIVERSE_PRECEDENCE,
    AmbiguousEventError,
    AsOfBook,
    AsOfError,
    AsOfSnapshot,
    DuplicateEventError,
    LabelObservation,
    MarketObservation,
    MissingLabelError,
    PointInTimePanel,
    UnavailableEventError,
    UniverseMembership,
    canonical_event_order,
)
from .checkpoint import (
    CheckpointCompatibilityError,
    CheckpointEnvelope,
    CheckpointError,
    CheckpointIntegrityError,
    checkpoint_from_components,
    load_checkpoint,
    restore_component_states,
    save_checkpoint,
)
from .economic import (
    ECONOMIC_EVIDENCE_SCHEMA,
    ECONOMIC_EVIDENCE_VERSION,
    ECONOMIC_SCHEMA,
    ECONOMIC_VERSION,
    EconomicDecision,
    EconomicEvaluationConfig,
    EconomicEvaluationError,
    EconomicEvaluationResult,
    EconomicEvidence,
    EconomicPathRow,
    ExecutionCost,
    RealizedReturn,
    evaluate_economic_evidence_path,
    evaluate_economic_path,
)
from .evidence import (
    EvidenceLedger,
    EvidenceResolution,
    FrozenPrediction,
    LabelReceipt,
    PromotionEvidenceConfig,
)
from .manifest import (
    MANIFEST_SCHEMA,
    MANIFEST_VERSION,
    STUDY_SCHEMA,
    STUDY_VERSION,
    ManifestValidationError,
    RunManifest,
    RunSpec,
    StudyManifest,
    StudySpec,
    StudyWindow,
)
from .replay import (
    MAX_REPLAY_DECISIONS,
    MAX_REPLAY_RECORDS,
    REPLAY_SCHEMA,
    REPLAY_VERSION,
    CausalReplay,
    CausalReplayResult,
    ReplayConfig,
    ReplayError,
    ReplayPrediction,
    ReplayRecord,
    ReplayResolution,
    ReplayState,
    ReplayStateError,
    ReplayStatus,
    run_causal_replay,
)
from .selection import (
    MAX_SELECTION_SLOTS,
    SELECTION_BUDGET_SCHEMA,
    SELECTION_BUDGET_VERSION,
    SelectionBudget,
)
from .types import (
    ArrayLike,
    BacktestConfig,
    BacktestDatasetProtocol,
    BacktesterProtocol,
    BacktestResult,
    BacktestResultProtocol,
    EProcessGateProtocol,
    EProcessState,
    GateDecision,
    GateStatus,
    Matrix,
    Metadata,
    Observation,
    PromotionDecisionProtocol,
    RLSLearnerProtocol,
    RLSState,
    RLSUpdate,
    Scalar,
    SyntheticConfig,
    SyntheticDataConfig,
    SyntheticDataFactoryProtocol,
    SyntheticDataGeneratorProtocol,
    TargetLike,
    Timestamp,
    TopologyDetectorProtocol,
    TopologyEstimate,
    TopologyResult,
    TopologyResultProtocol,
    TopologySignal,
    Vector,
)

# This is the single package-version source. setuptools reads the same
# attribute through ``tool.setuptools.dynamic`` in pyproject.toml.
__version__ = "0.1.0"

_LAZY_EXPORTS: dict[str, tuple[str, str]] = {
    "CausalFeaturePlan": (".causal_numeric", "CausalFeaturePlan"),
    "CausalNumericError": (".causal_numeric", "CausalNumericError"),
    "CausalRLSConfig": (".causal_numeric", "CausalRLSConfig"),
    "CausalRLSModel": (".causal_numeric", "CausalRLSModel"),
    "CausalRLSReplayResult": (".causal_numeric", "CausalRLSReplayResult"),
    "CausalStep": (".causal_numeric", "CausalStep"),
    "FeatureBinding": (".causal_numeric", "FeatureBinding"),
    "run_causal_rls_replay": (".causal_numeric", "run_causal_rls_replay"),
    "STUDY_INPUT_SCHEMA": (".study", "STUDY_INPUT_SCHEMA"),
    "STUDY_INPUT_VERSION": (".study", "STUDY_INPUT_VERSION"),
    "StudyInputAudit": (".study", "StudyInputAudit"),
    "StudyInputBundle": (".study", "StudyInputBundle"),
    "StudyInputError": (".study", "StudyInputError"),
    "StudyPromotionRunResult": (".study", "StudyPromotionRunResult"),
    "StudyRLSRunResult": (".study", "StudyRLSRunResult"),
    "StudyTimeline": (".study", "StudyTimeline"),
    "run_causal_promotion_study": (".study", "run_causal_promotion_study"),
    "run_causal_rls_study": (".study", "run_causal_rls_study"),
    "SOURCE_PACKAGE_SCHEMA": (".study_package", "SOURCE_PACKAGE_SCHEMA"),
    "SOURCE_PACKAGE_VERSION": (".study_package", "SOURCE_PACKAGE_VERSION"),
    "SOURCE_AUDIT_SCHEMA": (".study_package", "SOURCE_AUDIT_SCHEMA"),
    "SOURCE_AUDIT_VERSION": (".study_package", "SOURCE_AUDIT_VERSION"),
    "SOURCE_ARTIFACT_SCHEMA": (".study_package", "SOURCE_ARTIFACT_SCHEMA"),
    "SOURCE_ARTIFACT_VERSION": (".study_package", "SOURCE_ARTIFACT_VERSION"),
    "SOURCE_PROVENANCE_SCHEMA": (
        ".study_package",
        "SOURCE_PROVENANCE_SCHEMA",
    ),
    "SOURCE_PROVENANCE_VERSION": (
        ".study_package",
        "SOURCE_PROVENANCE_VERSION",
    ),
    "StudySourcePackage": (".study_package", "StudySourcePackage"),
    "StudySourcePackageError": (
        ".study_package",
        "StudySourcePackageError",
    ),
    "StudySourceArtifact": (".study_package", "StudySourceArtifact"),
    "StudySourceAudit": (".study_package", "StudySourceAudit"),
    "StudySourceProvenance": (".study_package", "StudySourceProvenance"),
    "REQUIRED_MARKET_ARTIFACT_ROLES": (
        ".study_package",
        "REQUIRED_MARKET_ARTIFACT_ROLES",
    ),
    "CausalPromotionActivation": (
        ".causal_promotion",
        "CausalPromotionActivation",
    ),
    "CausalPromotionConfig": (".causal_promotion", "CausalPromotionConfig"),
    "CausalPromotionError": (".causal_promotion", "CausalPromotionError"),
    "CausalPromotionModel": (".causal_promotion", "CausalPromotionModel"),
    "CausalPromotionReplayResult": (
        ".causal_promotion",
        "CausalPromotionReplayResult",
    ),
    "CausalPromotionStatus": (".causal_promotion", "CausalPromotionStatus"),
    "CausalPromotionStep": (".causal_promotion", "CausalPromotionStep"),
    "run_causal_promotion_replay": (
        ".causal_promotion",
        "run_causal_promotion_replay",
    ),
    "CalibrationConfig": (".calibration", "CalibrationConfig"),
    "CalibrationCertificate": (".calibration", "CalibrationCertificate"),
    "EProcessCalibrationConfig": (".calibration", "EProcessCalibrationConfig"),
    "EProcessNullCalibrationResult": (
        ".calibration",
        "EProcessNullCalibrationResult",
    ),
    "PromotionCalibrationConfig": (".calibration", "PromotionCalibrationConfig"),
    "PromotionNullCalibrationResult": (
        ".calibration",
        "PromotionNullCalibrationResult",
    ),
    "SelectionCalibrationConfig": (".calibration", "SelectionCalibrationConfig"),
    "SelectionNullCalibrationResult": (
        ".calibration",
        "SelectionNullCalibrationResult",
    ),
    "ThresholdCalibrationResult": (
        ".calibration",
        "ThresholdCalibrationResult",
    ),
    "StationaryBlockBootstrap": (".calibration", "StationaryBlockBootstrap"),
    "NullCalibrationResult": (".calibration", "NullCalibrationResult"),
    "ShiftCalibrationResult": (".calibration", "ShiftCalibrationResult"),
    "calibrate_null": (".calibration", "calibrate_null"),
    "calibrate_eprocess_null": (".calibration", "calibrate_eprocess_null"),
    "calibrate_promotion_null": (".calibration", "calibrate_promotion_null"),
    "calibrate_selection_null": (".calibration", "calibrate_selection_null"),
    "calibrate_threshold": (".calibration", "calibrate_threshold"),
    "calibrate_shift": (".calibration", "calibrate_shift"),
    "MeanCovarianceCUSUM": (".cpd", "MeanCovarianceCUSUM"),
    "MeanCovarianceCUSUMBatchResult": (".cpd", "MeanCovarianceCUSUMBatchResult"),
    "MeanCovarianceCUSUMConfig": (".cpd", "MeanCovarianceCUSUMConfig"),
    "MeanCovarianceCUSUMObservation": (".cpd", "MeanCovarianceCUSUMObservation"),
    "MEAN_COV_CUSUM_SCHEMA": (".cpd", "MEAN_COV_CUSUM_SCHEMA"),
    "MEAN_COV_CUSUM_VERSION": (".cpd", "MEAN_COV_CUSUM_VERSION"),
    "catoni_mean": (".experts", "catoni_mean"),
    "ExpertDecision": (".experts", "ExpertDecision"),
    "HeavyTailExpertAllocator": (".experts", "HeavyTailExpertAllocator"),
    "HeavyTailExpertConfig": (".experts", "HeavyTailExpertConfig"),
    "HEAVY_TAIL_EXPERT_SCHEMA": (".experts", "HEAVY_TAIL_EXPERT_SCHEMA"),
    "HEAVY_TAIL_EXPERT_VERSION": (".experts", "HEAVY_TAIL_EXPERT_VERSION"),
    "MAX_EXPERTS": (".experts", "MAX_EXPERTS"),
    "MAX_EXPERT_HISTORY": (".experts", "MAX_EXPERT_HISTORY"),
    "MECHANISM_SCHEMA": (".mechanisms", "MECHANISM_SCHEMA"),
    "MECHANISM_VERSION": (".mechanisms", "MECHANISM_VERSION"),
    "MechanismLocalizedConfig": (".mechanisms", "MechanismLocalizedConfig"),
    "MechanismLocalizedRLS": (".mechanisms", "MechanismLocalizedRLS"),
    "MechanismObservation": (".mechanisms", "MechanismObservation"),
    "MechanismSpec": (".mechanisms", "MechanismSpec"),
    "MechanismUpdate": (".mechanisms", "MechanismUpdate"),
    "CausalTransportReplay": (".transport", "CausalTransportReplay"),
    "TransportReplayBatch": (".transport", "TransportReplayBatch"),
    "TransportReplayConfig": (".transport", "TransportReplayConfig"),
    "TRANSPORT_REPLAY_SCHEMA": (".transport", "TRANSPORT_REPLAY_SCHEMA"),
    "TRANSPORT_REPLAY_VERSION": (".transport", "TRANSPORT_REPLAY_VERSION"),
    "PersistentLaplacianConfig": (".persistent", "PersistentLaplacianConfig"),
    "PersistentLaplacianBackend": (".persistent", "PersistentLaplacianBackend"),
    "PersistentLaplacianResult": (".persistent", "PersistentLaplacianResult"),
    "PERSISTENT_BACKEND_SCHEMA": (".persistent", "PERSISTENT_BACKEND_SCHEMA"),
    "PersistentSpectrum": (".persistent", "PersistentSpectrum"),
    "PersistentStatus": (".persistent", "PersistentStatus"),
    "compute_persistent_laplacian": (".persistent", "compute_persistent_laplacian"),
    "persistent_laplacian_backend": (".persistent", "persistent_laplacian_backend"),
    "PERSISTENT_CUSUM_SCHEMA": (".pl_cusum", "PERSISTENT_CUSUM_SCHEMA"),
    "PERSISTENT_CUSUM_VERSION": (".pl_cusum", "PERSISTENT_CUSUM_VERSION"),
    "PersistentCUSUMConfig": (".pl_cusum", "PersistentCUSUMConfig"),
    "PersistentCUSUMBatchResult": (".pl_cusum", "PersistentCUSUMBatchResult"),
    "PersistentCUSUMError": (".pl_cusum", "PersistentCUSUMError"),
    "PersistentCUSUMObservation": (".pl_cusum", "PersistentCUSUMObservation"),
    "PersistentLaplacianCUSUM": (".pl_cusum", "PersistentLaplacianCUSUM"),
    "AdaptiveRLS": (".rls", "AdaptiveRLS"),
    "RLSConfig": (".rls", "RLSConfig"),
    "RLS": (".rls", "RLS"),
    "BacktestEngine": (".backtest", "BacktestEngine"),
    "WalkForwardResult": (".backtest", "BacktestResult"),
    "WorkerBacktestConfig": (".backtest", "BacktestConfig"),
    "EProcess": (".promotion", "EProcess"),
    "PromotionGateStatus": (".promotion", "GateStatus"),
    "PromotionDecision": (".promotion", "PromotionDecision"),
    "PromotionGate": (".promotion", "PromotionGate"),
    "PromotionStatus": (".promotion", "PromotionStatus"),
    "RollingTopologyDetector": (".topology", "RollingTopologyDetector"),
    "StreamingTopologyResult": (".topology", "StreamingTopologyResult"),
    "DetectedTopologyResult": (".topology", "TopologyResult"),
    "SyntheticDataset": (".synthetic", "SyntheticDataset"),
    "SyntheticRegimeProcess": (".synthetic", "SyntheticRegimeProcess"),
    "TimeIndexedFeatures": (".synthetic", "TimeIndexedFeatures"),
    "TimeIndexedLabels": (".synthetic", "TimeIndexedLabels"),
    "TopologyConfig": (".topology", "TopologyConfig"),
    "WalkForwardBacktest": (".backtest", "WalkForwardBacktest"),
    "WalkForwardBacktester": (".backtest", "WalkForwardBacktester"),
    "WalkForwardConfig": (".backtest", "WalkForwardConfig"),
    "ModelConfig": (".config", "ModelConfig"),
    "OnlineRunConfig": (".online", "OnlineRunConfig"),
    "OnlineRunResult": (".online", "OnlineRunResult"),
    "OnlineStreamState": (".online", "OnlineStreamState"),
    "ONLINE_STREAM_SCHEMA": (".online", "ONLINE_STREAM_SCHEMA"),
    "ONLINE_STREAM_VERSION": (".online", "ONLINE_STREAM_VERSION"),
    "PendingLabelRecord": (".online", "PendingLabelRecord"),
    "run_recursive_rls": (".online", "run_recursive_rls"),
    "generate_regime_switching": (".synthetic", "generate_regime_switching"),
    "generate_synthetic_regimes": (".synthetic", "generate_synthetic_regimes"),
}

# These workers import NumPy eagerly. Keeping this set explicit lets the root
# boundary preserve a useful standard-library-only import while giving a
# precise hint when a caller asks for a numerical worker without its extra.
_NUMERIC_WORKER_MODULES = frozenset(
    {
        ".backtest",
        ".calibration",
        ".causal_numeric",
        ".causal_promotion",
        ".online",
        ".persistent",
        ".pl_cusum",
        ".synthetic",
    }
)


def _optional_dependency_error(
    name: str,
    error: ModuleNotFoundError,
) -> ImportError:
    missing = error.name or "an optional dependency"
    return ImportError(
        f"topology_gate.{name} requires the optional numerical worker "
        f"dependencies (missing {missing!r}). Install them with "
        "`python -m pip install 'topology-gate[numeric]'` or use the "
        "`test`/`dev` extra for the release toolchain."
    )


def __getattr__(name: str) -> Any:
    """Resolve worker implementations without importing optional dependencies."""

    target = _LAZY_EXPORTS.get(name)
    if target is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attribute_name = target
    try:
        value = getattr(import_module(module_name, __name__), attribute_name)
    except ModuleNotFoundError as exc:
        if module_name in _NUMERIC_WORKER_MODULES:
            raise _optional_dependency_error(name, exc) from exc
        raise
    globals()[name] = value
    return value


def __dir__() -> list[str]:
    return sorted(set(globals()) | set(_LAZY_EXPORTS))


__all__ = [
    "ASOF_BOOK_SCHEMA",
    "ASOF_BOOK_VERSION",
    "AdaptiveRLS",
    "AmbiguousEventError",
    "ArrayLike",
    "AsOfBook",
    "AsOfError",
    "AsOfSnapshot",
    "BacktestConfig",
    "BacktestDatasetProtocol",
    "BacktestEngine",
    "BacktestResult",
    "BacktestResultProtocol",
    "BacktesterProtocol",
    "CalibrationConfig",
    "CalibrationCertificate",
    "StationaryBlockBootstrap",
    "EProcessCalibrationConfig",
    "EProcessNullCalibrationResult",
    "PromotionCalibrationConfig",
    "PromotionNullCalibrationResult",
    "SelectionCalibrationConfig",
    "SelectionNullCalibrationResult",
    "ThresholdCalibrationResult",
    "CausalFeaturePlan",
    "CausalNumericError",
    "CausalPromotionActivation",
    "CausalPromotionConfig",
    "CausalPromotionError",
    "CausalPromotionModel",
    "CausalPromotionReplayResult",
    "CausalPromotionStatus",
    "CausalPromotionStep",
    "CausalRLSConfig",
    "CausalRLSModel",
    "CausalRLSReplayResult",
    "CausalReplay",
    "CausalReplayResult",
    "CausalStep",
    "CheckpointCompatibilityError",
    "CheckpointEnvelope",
    "CheckpointError",
    "CheckpointIntegrityError",
    "DetectedTopologyResult",
    "DuplicateEventError",
    "EvidenceLedger",
    "EvidenceResolution",
    "EProcess",
    "EProcessGateProtocol",
    "EProcessState",
    "ECONOMIC_SCHEMA",
    "ECONOMIC_VERSION",
    "ECONOMIC_EVIDENCE_SCHEMA",
    "ECONOMIC_EVIDENCE_VERSION",
    "EconomicDecision",
    "EconomicEvidence",
    "EconomicEvaluationConfig",
    "EconomicEvaluationError",
    "EconomicEvaluationResult",
    "EconomicPathRow",
    "ExecutionCost",
    "GateDecision",
    "GateStatus",
    "FrozenPrediction",
    "FeatureBinding",
    "LabelReceipt",
    "LABEL_PRECEDENCE",
    "LabelObservation",
    "MARKET_PRECEDENCE",
    "MarketObservation",
    "PointInTimePanel",
    "MANIFEST_SCHEMA",
    "MANIFEST_VERSION",
    "ManifestValidationError",
    "Matrix",
    "Metadata",
    "MissingLabelError",
    "ModelConfig",
    "Observation",
    "NullCalibrationResult",
    "OnlineRunConfig",
    "OnlineRunResult",
    "OnlineStreamState",
    "ONLINE_STREAM_SCHEMA",
    "ONLINE_STREAM_VERSION",
    "PendingLabelRecord",
    "PersistentLaplacianConfig",
    "PersistentLaplacianBackend",
    "PersistentLaplacianResult",
    "PersistentSpectrum",
    "PersistentStatus",
    "PERSISTENT_BACKEND_SCHEMA",
    "PERSISTENT_CUSUM_SCHEMA",
    "PERSISTENT_CUSUM_VERSION",
    "PersistentCUSUMConfig",
    "PersistentCUSUMBatchResult",
    "PersistentCUSUMError",
    "PersistentCUSUMObservation",
    "PersistentLaplacianCUSUM",
    "PromotionDecision",
    "PromotionEvidenceConfig",
    "PromotionDecisionProtocol",
    "PromotionGate",
    "PromotionGateStatus",
    "PromotionStatus",
    "ReplayConfig",
    "ReplayError",
    "ReplayPrediction",
    "ReplayRecord",
    "ReplayResolution",
    "ReplayState",
    "ReplayStateError",
    "ReplayStatus",
    "REPLAY_SCHEMA",
    "REPLAY_VERSION",
    "RLS",
    "RLSConfig",
    "RLSLearnerProtocol",
    "RLSState",
    "RLSUpdate",
    "RealizedReturn",
    "RunManifest",
    "RunSpec",
    "STUDY_SCHEMA",
    "STUDY_VERSION",
    "StudyManifest",
    "StudySpec",
    "StudyWindow",
    "STUDY_INPUT_SCHEMA",
    "STUDY_INPUT_VERSION",
    "StudyInputAudit",
    "StudyInputBundle",
    "StudyInputError",
    "StudyPromotionRunResult",
    "StudyRLSRunResult",
    "StudyTimeline",
    "SOURCE_PACKAGE_SCHEMA",
    "SOURCE_PACKAGE_VERSION",
    "SOURCE_AUDIT_SCHEMA",
    "SOURCE_AUDIT_VERSION",
    "SOURCE_ARTIFACT_SCHEMA",
    "SOURCE_ARTIFACT_VERSION",
    "SOURCE_PROVENANCE_SCHEMA",
    "SOURCE_PROVENANCE_VERSION",
    "StudySourcePackage",
    "StudySourcePackageError",
    "StudySourceArtifact",
    "StudySourceAudit",
    "StudySourceProvenance",
    "REQUIRED_MARKET_ARTIFACT_ROLES",
    "RollingTopologyDetector",
    "Scalar",
    "ShiftCalibrationResult",
    "SelectionBudget",
    "SELECTION_BUDGET_SCHEMA",
    "SELECTION_BUDGET_VERSION",
    "MAX_SELECTION_SLOTS",
    "CausalTransportReplay",
    "TransportReplayBatch",
    "TransportReplayConfig",
    "TRANSPORT_REPLAY_SCHEMA",
    "TRANSPORT_REPLAY_VERSION",
    "MeanCovarianceCUSUM",
    "MeanCovarianceCUSUMBatchResult",
    "MeanCovarianceCUSUMConfig",
    "MeanCovarianceCUSUMObservation",
    "MEAN_COV_CUSUM_SCHEMA",
    "MEAN_COV_CUSUM_VERSION",
    "catoni_mean",
    "ExpertDecision",
    "HeavyTailExpertAllocator",
    "HeavyTailExpertConfig",
    "HEAVY_TAIL_EXPERT_SCHEMA",
    "HEAVY_TAIL_EXPERT_VERSION",
    "MAX_EXPERTS",
    "MAX_EXPERT_HISTORY",
    "MECHANISM_SCHEMA",
    "MECHANISM_VERSION",
    "MechanismLocalizedConfig",
    "MechanismLocalizedRLS",
    "MechanismObservation",
    "MechanismSpec",
    "MechanismUpdate",
    "StreamingTopologyResult",
    "SyntheticConfig",
    "SyntheticDataConfig",
    "SyntheticDataFactoryProtocol",
    "SyntheticDataGeneratorProtocol",
    "SyntheticDataset",
    "SyntheticRegimeProcess",
    "TargetLike",
    "TimeIndexedFeatures",
    "TimeIndexedLabels",
    "Timestamp",
    "TopologyConfig",
    "TopologyDetectorProtocol",
    "TopologyEstimate",
    "TopologyResult",
    "TopologyResultProtocol",
    "TopologySignal",
    "UNIVERSE_PRECEDENCE",
    "UnavailableEventError",
    "UniverseMembership",
    "Vector",
    "WalkForwardBacktest",
    "WalkForwardBacktester",
    "WalkForwardConfig",
    "WalkForwardResult",
    "WorkerBacktestConfig",
    "MAX_REPLAY_DECISIONS",
    "MAX_REPLAY_RECORDS",
    "__version__",
    "generate_regime_switching",
    "generate_synthetic_regimes",
    "checkpoint_from_components",
    "canonical_event_order",
    "calibrate_null",
    "calibrate_eprocess_null",
    "calibrate_promotion_null",
    "calibrate_threshold",
    "calibrate_shift",
    "compute_persistent_laplacian",
    "load_checkpoint",
    "restore_component_states",
    "run_recursive_rls",
    "run_causal_replay",
    "run_causal_rls_replay",
    "run_causal_rls_study",
    "run_causal_promotion_study",
    "run_causal_promotion_replay",
    "evaluate_economic_path",
    "evaluate_economic_evidence_path",
    "save_checkpoint",
    "persistent_laplacian_backend",
]
